#!/usr/bin/env python

from __future__ import print_function
import subprocess
import os.path as p
import sys

d = p.dirname(p.realpath(__file__))
waf_light = p.join(d, '..', 'ardupilot', 'modules', 'waf', 'waf-light')
python = sys.executable

subprocess.check_call([python, waf_light] + sys.argv[1:])
